# Generated by Django 4.2.5 on 2023-10-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Game',
        ),
    ]
